spring.application.name=demo

# 引入ollama模型
# 云端接口
spring.ai.ollama.base-url=https://ollama.com
# 自定义认证token（云端需要通过 OllamaConfig 配置类使用）
ollama.auth.bearer-token=99ebf30eac79485089995ffccddefb37.gu8Y2XSqKnzntgNr4YPPZHNd
spring.ai.ollama.chat.options.model=qwen3-vl:235b-cloud
#使用本地模型（处理视频太慢了）
# spring.ai.ollama.base-url=http://localhost:11434  
# spring.ai.ollama.chat.options.model=qwen2.5vl:3b
spring.ai.ollama.init.pull-model-strategy=never

# MongoDB配置（未在mongodb的admin表中创建用户密码时使用）
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=content_moderation
# 使用URI连接字符串
# spring.data.mongodb.uri=mongodb://root:742903@localhost:27017/content_moderation


# 需要在pom引入spring-boot-configuration-processor，还有配置绑定类configuration/UploadConfiguration.java和UploadController.java
# 要使照片上传独立在项目外
# spring内置的tomcat对照片大小有限制
application.upload-root=D:\\Project\\upload
# 配置静态资源映射，让上传的文件可以通过HTTP访问
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/static/,classpath:/public/,classpath:/resources/,file:${application.upload-root}

# 上传大小限制（解决 413 Payload Too Large）
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 增加超时时间以支持视频处理
# 1分钟等于6万毫秒
server.tomcat.connection-timeout=300000
spring.mvc.async.request-timeout=300000

# 视频审核并行处理（线程池）
# 任务执行
spring.task.execution.mode=force
spring.task.execution.pool.core-size=6
spring.task.execution.pool.max-size=8
spring.task.execution.pool.queue-capacity=100
spring.task.execution.pool.keep-alive=10s
spring.task.execution.thread-name-prefix=video-task-
# 任务调度
spring.task.scheduling.thread-name-prefix=scheduling-
spring.task.scheduling.pool.size=2